cursor_trail 3
cursor_trail_decay 0.1 0.4

confirm_os_window_close 0

allow_remote_control yes

include ~/.cache/wal/colors-kitty.conf

background_opacity 0.7
background_blur 1
dynamic_background_opacity yes

listen_on unix:/tmp/mykitty
