$font = JetBrainsMono Nerd Font Propo
$main_monitor = HDMI-A-1

general {
    hide_cursor = false
    grace = 0
    disable_loading = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = /home/silly/.cache/wallpaper/wallpaper.*
    blur_passes = 5
    blur_size = 5
}

input-field {
    monitor = $main_monitor
    size = 150, 60
    outline_thickness = 3

    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgba(0, 0, 0, 0.0)

    check_color = $red
    fail_color = $red

    font_color = rgba(255, 255, 255, 0.5)
    fade_on_empty = false
    rounding = 30

    font_family = $font
    placeholder_text =
    fail_text =

    dots_text_format = *
    dots_size = 0.4
    dots_spacing = 0.3

    position = 0, 80
    halign = center
    valign = bottom
}

label {
    monitor = $main_monitor
    text = cmd[update:1] date +"%l:%M"
    font_size = 120
    font_family = $font black
    position = 0, -200
    halign = center
    valign = top
    color = rgba($textAlpha55)
}

label {
    monitor = $main_monitor
    text = cmd[update:1] date +"%a"
    font_size = 16
    font_family = $font
    position = -150, -380
    halign = center
    valign = top
    color = $text
}

label {
    monitor = $main_monitor
    text = 
    font_size = 14
    font_family = $font
    position = -100, -382
    halign = center
    valign = top
    color = $red
}

label {
    monitor = $main_monitor
    text = cmd[update:1] date +"%e"
    font_size = 16
    font_family = $font
    position = -50, -380
    halign = center
    valign = top
    color = $text
}

label {
    monitor = $main_monitor
    text = 
    font_size = 14
    font_family = $font
    position = 0, -382
    halign = center
    valign = top
    color = $green
}

label {
    monitor = $main_monitor
    text = cmd[update:1] date +"%b"
    font_size = 16
    font_family = $font
    position = 50, -380
    halign = center
    valign = top
    color = $text
}

label {
    monitor = $main_monitor
    text = 
    font_size = 14
    font_family = $font
    position = 100, -382
    halign = center
    valign = top
    color = $blue
}

label {
    monitor = $main_monitor
    text = cmd[update:1] date +"%Y"
    font_size = 16
    font_family = $font
    position = 150, -380
    halign = center
    valign = top
    color = $text
}
